"""add password to Rider

Revision ID: 1d4c77fd0894
Revises: 7902685c24a7
Create Date: 2025-06-28 10:16:28.223520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d4c77fd0894'
down_revision: Union[str, Sequence[str], None] = '7902685c24a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'store_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('riders', sa.Column('password', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('riders', 'password')
    op.alter_column('orders', 'store_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
