"""update ads model

Revision ID: 7902685c24a7
Revises: de9666d4f1e2
Create Date: 2025-06-28 06:25:55.622679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7902685c24a7'
down_revision: Union[str, Sequence[str], None] = 'de9666d4f1e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ads_id'), 'ads', ['id'], unique=False)
    op.add_column('orders', sa.Column('amount', sa.Numeric(), nullable=True))
    op.drop_column('orders', 'total_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('total_amount', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.drop_column('orders', 'amount')
    op.drop_index(op.f('ix_ads_id'), table_name='ads')
    op.drop_table('ads')
    # ### end Alembic commands ###
